### ISSUE TITLE
SM3D Land Crashes

### ISSUE THREAD

**Issue by Schneiderus** [mariohackandglitch/OnionFS#2]
Hey, the console crashes (ARM11 Error) when I launch Super Mario 3D Land (EUR), just after the blue screen during the "Nintendo 3DS" animation.

[crash_dump_00000000.zip](https://github.com/mariohackandglitch/OnionFS/files/4493779/crash_dump_00000000.zip)

Other game like NSMB2 works fine.

**Comment by lucasaf04** [comment]
I also get that error. I also tried with boot_v2.firm from cgtp7 updates and with that firm it says “outdated plugin format”.

**Comment by PabloMK7** [comment]
Fixed, thanks to @lucasaf04 for their help!
